// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv9HI_fDJkB-stFbaSSMv9_wi52rntM0E',
    appId: '1:479482442169:android:333e3839e429b73e960668',
    messagingSenderId: '479482442169',
    projectId: 'socialmistry-guides',
    storageBucket: 'socialmistry-guides.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd8FMCbhnEL5vbvB0FqZeRQyh4HHOSYxI',
    appId: '1:479482442169:web:ae171760ac2b0b3a960668',
    messagingSenderId: '479482442169',
    projectId: 'socialmistry-guides',
    authDomain: 'socialmistry-guides.firebaseapp.com',
    storageBucket: 'socialmistry-guides.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJLDc28jJaL7xVB9I-F6mGyPXhljSgIzs',
    appId: '1:479482442169:ios:5bcb420a71ee5baa960668',
    messagingSenderId: '479482442169',
    projectId: 'socialmistry-guides',
    storageBucket: 'socialmistry-guides.firebasestorage.app',
    iosBundleId: 'com.socialmistry.flutterAuthDemo',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJLDc28jJaL7xVB9I-F6mGyPXhljSgIzs',
    appId: '1:479482442169:ios:5bcb420a71ee5baa960668',
    messagingSenderId: '479482442169',
    projectId: 'socialmistry-guides',
    storageBucket: 'socialmistry-guides.firebasestorage.app',
    iosBundleId: 'com.socialmistry.flutterAuthDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd8FMCbhnEL5vbvB0FqZeRQyh4HHOSYxI',
    appId: '1:479482442169:web:bb7f8dc731aa9672960668',
    messagingSenderId: '479482442169',
    projectId: 'socialmistry-guides',
    authDomain: 'socialmistry-guides.firebaseapp.com',
    storageBucket: 'socialmistry-guides.firebasestorage.app',
  );

}